Repository FIWARE-Ops/data-space-connector, pull requests merged in 2024-07, with the labels that each got.

#80 Remove argocd
  .github/dependabot.yml
  .github/workflows/deploy.yaml
  README.md
  argocd/applications/activation-service/Chart.yaml
  argocd/applications/activation-service/values.yaml
  argocd/applications/contract-management/Chart.yaml
  argocd/applications/contract-management/values.yaml
  argocd/applications/credentials-config-service/Chart.yaml
  argocd/applications/credentials-config-service/values.yaml
  argocd/applications/dsba-pdp/Chart.yaml
  argocd/applications/dsba-pdp/values.yaml
  argocd/applications/keycloak/Chart.yaml
  argocd/applications/keycloak/templates/_helpers.tpl
  argocd/applications/keycloak/templates/certificate.yaml
  argocd/applications/keycloak/templates/didConfigMap.yaml
  argocd/applications/keycloak/templates/profilesConfigMap.yaml
  argocd/applications/keycloak/templates/route.yaml
  argocd/applications/keycloak/values.yaml
  argocd/applications/keyrock/Chart.yaml
  argocd/applications/keyrock/values.yaml
  argocd/applications/kong/Chart.yaml
  argocd/applications/kong/templates/_helpers.tpl
  argocd/applications/kong/templates/proxy-certificate.yaml
  argocd/applications/kong/templates/proxy-route.yaml
  argocd/applications/kong/values.yaml
  argocd/applications/mongodb/Chart.yaml
  argocd/applications/mongodb/values.yaml
  argocd/applications/mysql/Chart.yaml
  argocd/applications/mysql/values.yaml
  argocd/applications/orion-ld/Chart.yaml
  argocd/applications/orion-ld/values.yaml
  argocd/applications/postgres/Chart.yaml
  argocd/applications/postgres/values.yaml
  argocd/applications/tm-forum-api/Chart.yaml
  argocd/applications/tm-forum-api/values.yaml
  argocd/applications/trusted-issuers-list/Chart.yaml
  argocd/applications/trusted-issuers-list/values.yaml
  argocd/applications/vcwaltid/Chart.yaml
  argocd/applications/vcwaltid/templates/_helpers.tpl
  argocd/applications/vcwaltid/templates/certificate.yaml
  argocd/applications/vcwaltid/templates/deployment.yaml
  argocd/applications/vcwaltid/templates/ingress-certs.yaml
  argocd/applications/vcwaltid/templates/ingress.yaml
  argocd/applications/vcwaltid/templates/route-certs.yaml
  argocd/applications/vcwaltid/templates/route.yaml
  argocd/applications/vcwaltid/templates/service.yaml
  argocd/applications/vcwaltid/values.yaml
  argocd/applications/verifier/Chart.yaml
  argocd/applications/verifier/values.yaml
  argocd/data-space-connector/Chart.yaml
  argocd/data-space-connector/templates/_helpers.tpl
  argocd/data-space-connector/templates/argo-application.yaml
  argocd/data-space-connector/values.yaml
  examples/README.md
Labels: minor

#79 Add data-space-configuration endpoint
  charts/data-space-connector/Chart.yaml
  charts/data-space-connector/templates/dsconfig-cm.yaml
  charts/data-space-connector/templates/dsconfig-deployment.yaml
  charts/data-space-connector/templates/dsconfig-service.yaml
  charts/data-space-connector/values.yaml
  k3s/provider.yaml
Labels: minor

#82 Bump: Fix labels
  README.md
Labels: patch

#83 Cleanup
  .github/workflows/release-helm.yaml
Labels: patch

#84 Increase default resources of apisix
  charts/data-space-connector/Chart.yaml
  charts/data-space-connector/values.yaml
Labels: patch

#85 Add remark about archiving this repository
  README.md
Labels: major
